#!/usr/bin/env bash
# Prints a Homebrew formula for a published sshire release to stdout.
#
#   scripts/homebrew-formula.sh <version> <SHA256SUMS file> <owner/repo>
#
# Example:
#   scripts/homebrew-formula.sh 0.1.0 dist/SHA256SUMS octocat/sshire > Formula/sshire.rb
#
# The formula installs the prebuilt binaries from the GitHub release
# (macOS universal, Linux x86_64 / aarch64), so users don't need Rust.
set -euo pipefail

if [[ $# -ne 3 ]]; then
  echo "usage: $0 <version> <SHA256SUMS> <owner/repo>" >&2
  exit 2
fi

VERSION="$1"
SUMS="$2"
REPO="$3"
BASE="https://github.com/$REPO/releases/download/v$VERSION"

# Looks up the checksum of one archive in SHA256SUMS; fails if it is missing.
sha() {
  local file="sshire-$VERSION-$1.tar.gz" sum
  sum="$(awk -v f="$file" '$2 == f { print $1 }' "$SUMS")"
  if [[ -z "$sum" ]]; then
    echo "error: $file not found in $SUMS" >&2
    exit 1
  fi
  echo "$sum"
}

MAC_SHA="$(sha macos-universal)"
LINUX_X86_SHA="$(sha linux-x86_64)"
LINUX_ARM_SHA="$(sha linux-aarch64)"

cat <<EOF
# Generated by scripts/homebrew-formula.sh in $REPO – do not edit by hand.
class Sshire < Formula
  desc "TUI SSH launcher with host management, tags, connection log and password storage"
  homepage "https://github.com/$REPO"
  version "$VERSION"
  license any_of: ["MIT", "Apache-2.0"]

  # Plain if-branches instead of on_macos/on_linux blocks: Homebrew style rules
  # do not allow url/sha256 inside on_* blocks.
  if OS.mac?
    url "$BASE/sshire-$VERSION-macos-universal.tar.gz"
    sha256 "$MAC_SHA"
  elsif Hardware::CPU.arm?
    url "$BASE/sshire-$VERSION-linux-aarch64.tar.gz"
    sha256 "$LINUX_ARM_SHA"
  else
    url "$BASE/sshire-$VERSION-linux-x86_64.tar.gz"
    sha256 "$LINUX_X86_SHA"
  end

  def install
    bin.install "sshire"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sshire --version")
  end
end
EOF
